### ISSUE TITLE
Draggables within positioned containers

### ISSUE THREAD

**Issue by adam77** [caitp/angular-drop#63]
Using position:absolute for draggables doesn't seem to work for elements with positioned ancestors. The element is offset from the cursor by the ancestor's offset.
This happens because the draggables final position is the calculated offset (i.e. event position) plus ancestor offset.

Is this a known issue?
Any particular reason fixed positioning was not used during drag?

Thanks.

**Comment by caitp** [comment]
Would you be interested in sending a PR?

The design was based on jQuery ui's drag/drop, but some corners were cut for simplicity. Broken use cases certainly warrant more work though

**Comment by adam77** [comment]
Sure, I suppose calculating correct offset for absolute is better than going position:fixed?

drag/drop seems to be a big hole in the (pure)Angular eco-system, maybe i'm missing something...

**Comment by adam77** [comment]
seems to be no official browser support so I'm assuming IE9+.

**Comment by caitp** [comment]
Angular 1.4's browser support is ie9+, blink opera, and I think we still test on safari 6. This project is only doing limited browser testing because money, but the goal is to match core angular browser support.
